<?php

/**
 * @file
 * Primary module hooks for Simple School Reports Class Support module.
 */

use Drupal\Core\Render\Element;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\simple_school_reports_class_support\Service\SsrClassServiceInterface;

/**
 * Implements hook_theme().
 */
function simple_school_reports_class_support_theme(): array {
  return [
    'ssr_school_class' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for school class templates.
 *
 * Default template: ssr-school-class.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the school class information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_ssr_school_class(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

function simple_school_reports_dnp_support_student_suffix_options(): array {
  return [
    SsrClassServiceInterface::STUDENT_SUFFIX_DEFAULT => t('Default (only grade), example: Anders Andersson (Gr 3)'),
    SsrClassServiceInterface::STUDENT_SUFFIX_CLASS => t('Class (only class name), example: Anders Andersson (3A)'),
    SsrClassServiceInterface::STUDENT_SUFFIX_CLASS_GRADE => t('Class and grade, example: Anders Andersson (1-3A Gr 3)'),
  ];
}

/**
 * Implements hook_entity_field_access().
 */
function simple_school_reports_class_support_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, ?FieldItemListInterface $items = NULL) {
  $class_fields = [
    'field_class',
    'field_classes',
    'field_use_classes',
  ];

  if (in_array($field_definition->getName(), $class_fields)) {
    /** @var \Drupal\Core\Extension\ModuleHandlerInterface $module_handler */
    $module_handler = \Drupal::service('module_handler');

    return AccessResult::forbiddenIf(!$module_handler->moduleExists('simple_school_reports_class'));
  }

  if ($field_definition->getTargetEntityTypeId() === 'ssr_school_class' && $field_definition->getName() === 'school_week') {
    /** @var \Drupal\Core\Extension\ModuleHandlerInterface $module_handler */
    $module_handler = \Drupal::service('module_handler');
    return AccessResult::forbiddenIf(!$module_handler->moduleExists('simple_school_reports_attendance_analyse'));
  }

  return AccessResult::neutral();
}

function ssr_views_permission_access_to_classes_list() {
  $account = \Drupal::currentUser();
  $access = AccessResult::allowedIf($account->hasPermission('create ssr_school_class') && \Drupal::moduleHandler()->moduleExists('simple_school_reports_class'));
  $access->cachePerPermissions();
  return $access;
}

/**
 * Implements hook_views_data_alter().
 */
function simple_school_reports_class_support_views_data_alter(array &$data) {
  if (isset($data['ssr_school_class_field_data'])) {
    // Copy id data to number_of_students.
    $data['ssr_school_class_field_data']['number_of_students'] = $data['ssr_school_class_field_data']['id'];
    // Override title and override views field.
    $data['ssr_school_class_field_data']['number_of_students']['title'] = t('Number of students');
    $data['ssr_school_class_field_data']['number_of_students']['help'] =  t('Show number of students in the class.');
    $data['ssr_school_class_field_data']['number_of_students']['field'] = [
      'id' => 'ssr_school_class_number_of_students',
    ];
  }
}

