<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\simple_school_reports_grade_stats\GradeStatisticsFormAlter;

/**
 * Implements hook_form_alter().
 */
function simple_school_reports_grade_stats_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $forms_to_alter = ['node_grade_statistics_edit_form', 'node_grade_statistics_form'];
  if (in_array($form_id, $forms_to_alter)) {
    GradeStatisticsFormAlter::formAlter($form, $form_state);
  }
}

/**
 * Implements hook_entity_operation_alter().
 */
function simple_school_reports_grade_stats_entity_operation_alter(array &$operations, \Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity instanceof \Drupal\node\NodeInterface) {
    if ($entity->bundle() === 'grade_statistics') {
      $operations['view_gs'] = [
        'title' => t('View/Print'),
        'url' => \Drupal\Core\Url::fromRoute('entity.node.canonical', ['node' => $entity->id()], ['query' => ['destination' => \Drupal::service('path.current')->getPath()]]),
        'weight' =>  -99,
      ];
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function simple_school_reports_grade_stats_user_update(\Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity instanceof \Drupal\user\UserInterface && $entity->hasField('field_gender')) {
    $new_gender = $entity->get('field_gender')->value ?? NULL;
    $old_gender = $entity->original && $entity->original->get('field_gender')->value ? $entity->original->get('field_gender')->value : NULL;
    if ($new_gender !== $old_gender) {
      \Drupal\Core\Cache\Cache::invalidateTags(['user_gender_change']);
    }
  }
}

/**
 * Implements hook_ssr_local_actions_alter().
 */
function simple_school_reports_grade_stats_ssr_local_actions_alter(array &$local_actions, \Drupal\Core\Cache\CacheableMetadata $cache, array $context) {
  if ($context['route_name'] === 'entity.node.canonical') {
    $grade_statistics_node = $context['current_request']->get('node');
    if ($grade_statistics_node instanceof \Drupal\node\NodeInterface && $grade_statistics_node->bundle() === 'grade_statistics') {
      $cache->addCacheableDependency($grade_statistics_node);
      $cache->addCacheContexts(['user.permissions']);

      $local_actions['print_action'] = [
        '#theme' => 'menu_local_action',
        '#link' => [
          'title' => t('Print out'),
          'url' => \Drupal\Core\Url::fromUserInput('#'),
          'localized_options' => [
            'attributes' => [
              'class' => [
                'action--ssr-print',
              ],
            ],
          ],
        ],
        '#access' => \Drupal\Core\Access\AccessResult::allowedIf($grade_statistics_node->access('view')),
        '#weight' => 10,
      ];
    }
  }
}

