<?php

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\simple_school_reports_core\UserFormAlter;
use Drupal\simple_school_reports_iup\IUPFormAlter;
use Drupal\simple_school_reports_iup\IUPStandardPhraseFormAlter;
use Drupal\simple_school_reports_iup\IUPStandardGoalFormAlter;
use Drupal\simple_school_reports_iup\IUPGoalsFormAlter;

/**
 * Implements hook_form_alter().
 */
function simple_school_reports_iup_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $forms_to_alter = ['node_iup_round_edit_form', 'node_iup_round_form'];
  if (in_array($form_id, $forms_to_alter)) {
    IUPFormAlter::setDefaultDates($form, $form_state);
  }

  $forms_to_alter = ['node_iup_edit_form', 'node_iup_form'];
  if (in_array($form_id, $forms_to_alter)) {
    IUPFormAlter::formAlter($form, $form_state);
  }

  if ($form_id === 'views_exposed_form') {
    /** @var \Drupal\views\Entity\View $view */
    if ($view = $form_state->get('view')) {
      if ($view->id() === 'iup_student_list') {
        IUPFormAlter::exposedViewsFormAlter($form, $form_state);
        UserFormAlter::exposedFilterByClass($form, $form_state);
      }

      if ($view->id() === 'iup_goals') {
        IUPGoalsFormAlter::exposedViewsFormAlter($form, $form_state);
      }
    }
  }

  if ($form_id === 'taxonomy_term_iup_standard_phrase_form') {
    IUPStandardPhraseFormAlter::formAlter($form, $form_state);
  }

  if ($form_id === 'taxonomy_term_iup_standard_goal_form') {
    IUPStandardGoalFormAlter::formAlter($form, $form_state);
  }

  if ($form_id === 'node_iup_goal_edit_form') {
    IUPGoalsFormAlter::formAlter($form, $form_state);
  }
}

/**
 * Implements hook_entity_operation_alter().
 */
function simple_school_reports_iup_entity_operation_alter(array &$operations, \Drupal\Core\Entity\EntityInterface $entity) {

  if ($entity instanceof \Drupal\node\NodeInterface) {
    if ($entity->bundle() === 'iup_round') {
      $locked = $entity->get('field_locked')->value;
      $operations['iup_registration'] = [
        'title' => t('IUP registration'),
        'url' => \Drupal\Core\Url::fromRoute('view.iup_student_list.iup_student_list', ['node' => $entity->id()]),
        'weight' => $locked ? -98 : -99,
      ];

      if ($entity->access('update')) {
        $operations['generate_docs'] = [
          'title' => t('Generate documents'),
          'url' => \Drupal\Core\Url::fromRoute('simple_school_reports_iup.generate_iup_multiple_docs', ['node' => $entity->id()], ['query' => ['destination' => \Drupal::service('path.current')->getPath()]]),
          'weight' => $locked ? -99 : -98,
        ];
      }
    }
  }

  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($entity instanceof \Drupal\user\UserInterface) {
    if ($entity->hasRole('student')) {
      if ($route_name === 'view.iup_student_list.iup_student_list') {
        $operations = [];

        $node_storage = \Drupal::entityTypeManager()->getStorage('node');
        $operations = [];
        $iup_round_node = \Drupal::request()->get('node');

        if (is_numeric($iup_round_node)) {
          $iup_round_node = $node_storage->load($iup_round_node);
        }

        if ($iup_round_node instanceof \Drupal\node\NodeInterface && $iup_round_node->bundle() === 'iup_round') {
          if ($entity->access('update')) {
            $operations['written_reviews_router'] = [
              'title' => t('IUP'),
              'url' => \Drupal\Core\Url::fromRoute('simple_school_reports_iup.student_router', ['round_nid' => $iup_round_node->id(), 'student_uid' => $entity->id()], ['query' => ['post_save_destination' => \Drupal::service('path.current')->getPath()]]),
              'weight' => -99,
            ];
          }
        }
      }
    }
  }
}

/**
 * Implements hook_inline_entity_form_entity_form_alter().
 */
function simple_school_reports_iup_inline_entity_form_entity_form_alter(&$entity_form, FormStateInterface $form_state) {
  if (!empty($entity_form['#form_mode']) && $entity_form['#form_mode'] === 'iup_goal_ief') {
    IUPFormAlter::iefIUPGoalFormAlter($entity_form, $form_state);
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function simple_school_reports_iup_node_presave(\Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->bundle() === 'iup') {
    $student = $entity->get('field_student')->target_id;
    $iup_round = $entity->get('field_iup_round')->target_id;

    if ($student && $iup_round) {
      foreach ($entity->get('field_iup_goal_list')->referencedEntities() as $iup_goal) {
        $save = FALSE;

        if ($iup_goal->get('field_student')->target_id !== $student) {
          $iup_goal->set('field_student', ['target_id' => $student]);
          $save = TRUE;
        }
        if ($iup_goal->get('field_iup_round')->target_id !== $iup_round) {
          $iup_goal->set('field_iup_round', ['target_id' => $iup_round]);
          $save = TRUE;
        }

        if ($save) {
          $iup_goal->save();
        }
      }
    }


    if ($entity->get('field_state')->value !== 'done') {
      $entity->set('field_document_date', NULL);
    }
  }

  if ($entity->bundle() === 'iup_goal') {
    if ($entity->get('field_teacher_comment')->value) {
      $entity->set('field_state', 'done');
    }
    else {
      $entity->set('field_state', 'started');
    }
  }
}

/**
 * Implements hook_views_query_alter().
 */
function simple_school_reports_iup_views_query_alter(\Drupal\views\ViewExecutable $view, \Drupal\views\Plugin\views\query\QueryPluginBase $query) {
  if ($view->id() === 'iup_goals') {
    foreach ($query->where as &$condition_group) {
      foreach ($condition_group['conditions'] as $key => &$condition) {
        if (!empty($condition['field']) && $condition['field'] === 'node__field_iup_round.field_iup_round_target_id') {
          if ($condition['value'] === '0') {
            $node_storage = \Drupal::entityTypeManager()->getStorage('node');
            $iup_round_nid = current($node_storage->getQuery()
              ->accessCheck(FALSE)
              ->condition('type', 'iup_round')
              ->sort('field_document_date', 'DESC')
              ->sort('nid', 'DESC')
              ->range(0,1)
              ->execute());
            if ($iup_round_nid) {
              $condition['value'] = $iup_round_nid;
            }
          }
        }
      }
    }
  }
}

/**
 * Implements hook_ssr_local_actions_alter().
 */
function simple_school_reports_iup_ssr_local_actions_alter(array &$local_actions, \Drupal\Core\Cache\CacheableMetadata $cache, array $context) {
  if ($context['route_name'] === 'entity.node.canonical') {
    $iup_node = $context['current_request']->get('node');
    if ($iup_node instanceof \Drupal\node\NodeInterface && $iup_node->bundle() === 'iup') {
      $cache->addCacheableDependency($iup_node);
      $cache->addCacheContexts(['user']);
      $destination = $context['current_request']->get('destination');
      if (!$destination) {
        $destination = $context['path.current']->getPath();
      }
      $access = AccessResult::allowedIf($iup_node->access('view'));
      $local_actions['ssr_iup_file_gen'] = [
        '#theme' => 'menu_local_action',
        '#link' => [
          'title' => t('Generate IUP document'),
          'url' => Url::fromRoute('simple_school_reports_iup.generate_iup_single_doc', ['node' => $iup_node->id()], ['query' => ['destination' => $destination]]),
        ],
        '#access' => $access->andIf(AccessResult::allowedIfHasPermission(\Drupal::currentUser(), 'school staff permissions')),
        '#weight' => 10,
      ];

      $local_actions['print_action'] = [
        '#theme' => 'menu_local_action',
        '#link' => [
          'title' => t('Print out'),
          'url' => \Drupal\Core\Url::fromUserInput('#'),
          'localized_options' => [
            'attributes' => [
              'class' => [
                'action--ssr-print',
              ],
            ],
          ],
        ],
        '#access' => $access,
        '#weight' => 9,
      ];
    }
  }

  if ($context['route_name'] === 'view.iup_student_list.iup_student_list') {
    $nid = $context['current_request']->get('node');
    if ($nid) {
      $cache->addCacheTags(['node:' . $nid]);
      $cache->addCacheContexts(['user']);
      $destination = $context['current_request']->get('destination');
      if (!$destination) {
        $destination = $context['path.current']->getPath();
      }
      $access = \Drupal\Core\Access\AccessResult::allowedIf(\Drupal::currentUser()->hasPermission('administer simple school reports settings'));
      $local_actions['ssr_iup_file_gen'] = [
        '#theme' => 'menu_local_action',
        '#link' => [
          'title' => t('Generate documents'),
          'url' => \Drupal\Core\Url::fromRoute('simple_school_reports_iup.generate_iup_multiple_docs', ['node' => $nid], ['query' => ['destination' => $destination]]),
        ],
        '#access' => $access,
        '#weight' => 10,
      ];
    }
  }
}
