<?php

/**
 * @file
 * Primary module hooks for Simple School Reports Schema Support module.
 */

function ssr_use_schema(): bool {
  // TEMP!!!!!
  return TRUE;

  /** @var \Drupal\Core\Extension\ModuleHandlerInterface $module_handler */
  $module_handler = \Drupal::service('module_handler');

  return $module_handler->moduleExists('simple_school_reports_schema_ssr');
}

function ssr_views_permission_my_courses_to_report() {
  $account = \Drupal::currentUser();
  $access = \Drupal\Core\Access\AccessResult::allowedIf($account->hasPermission('school staff permissions') && ssr_use_schema());
  $access->cachePerPermissions();
  return $access;
}

function ssr_views_permission_all_courses_to_report() {
  $account = \Drupal::currentUser();
  $access = \Drupal\Core\Access\AccessResult::allowedIf($account->hasPermission('administer simple school reports settings') && ssr_use_schema());
  $access->cachePerPermissions();
  return $access;
}

function simple_school_reports_schema_support_schema_subgroups() {
  return [
    1 => '1',
    2 => '2',
//    3 => '3',
//    4 => '4',
//    5 => '5',
  ];
}

function simple_school_reports_schema_support_schema_periodicity_options() {
  return [
    'weekly' => t('Weekly'),
    'odd_weeks' => t('Odd weeks'),
    'even_weeks' => t('Even weeks'),
    'custom' => t('Specify periodicity'),
  ];
}

function simple_school_reports_schema_support_schema_custom_periodicity_options() {
  return [
    2 => t('Every second week'),
    3 => t('Every third week'),
    4 => t('Every fourth week'),
    5 => t('Every fifth week'),
  ];
}

function simple_school_reports_schema_support_schema_source_options() {
  return [
    'ssr' => t('Simple School Reports'),
  ];
}

/**
 * Implements hook_menu_links_discovered_alter().
 */
function simple_school_reports_schema_support_menu_links_discovered_alter(&$links) {
  if (ssr_use_schema()) {
    if (isset($links['courses.page.courses'])) {
      $links['courses.page.courses']['route_name'] = 'view.calendar_events_courses.my_courses';
    }
  }
}

/**
 * Implements hook_entity_operation_alter().
 */
function simple_school_reports_schema_support_entity_operation_alter(array &$operations, \Drupal\Core\Entity\EntityInterface $entity) {
  if (!ssr_use_schema()) {
    return;
  }

  if ($entity instanceof \Drupal\simple_school_reports_entities\CalendarEventInterface) {
    if ($entity->bundle() === 'course') {
      $course = $entity->get('field_course')->entity;
      if ($course?->access('update')) {
        $operations['report'] = [
          'title' => t('Report'),
          'url' => \Drupal\Core\Url::fromRoute('node.add', ['node_type' => 'course_attendance_report'], ['query' => ['destination' => \Drupal::service('path.current')->getPath(), 'course_id' => $course->id(), 'calendar_event' => $entity->id()]]),
          'weight' => -99,
        ];

        $operations['fast_report'] = [
          'title' => t('Fast report'),
          'url' => \Drupal\Core\Url::fromRoute('simple_school_reports_schema.fast_report', ['node' => $course->id(), 'ssr_calendar_event' => $entity->id()], ['query' => ['destination' => \Drupal::service('path.current')->getPath()]]),
          'weight' => -98,
        ];

        $operations['cancel'] = [
          'title' => t('Cancel lesson'),
          'url' => \Drupal\Core\Url::fromRoute('simple_school_reports_schema.cancel_event', ['node' => $course->id(), 'ssr_calendar_event' => $entity->id()], ['query' => ['destination' => \Drupal::service('path.current')->getPath()]]),
          'weight' => -97,
        ];
      }
    }
  }
}

/**
 * Implements hook_views_pre_view().
 */
function simple_school_reports_schema_support_views_pre_view(\Drupal\views\ViewExecutable $view, $display_id, array &$args) {
  if ($view->id() === 'calendar_events_courses') {
    $view->element['#cache']['contexts'][] = 'user.node_grants';
    $view->element['#cache']['contexts'][] = 'user.permissions';
  }
}
