<?php

declare(strict_types=1);

/**
 * @file
 * Provides a child care module.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function simple_school_reports_child_care_support_theme(): array {
  return [
    'ssr_child_care' => ['render element' => 'elements'],
    'ssr_child_care_placement' => ['render element' => 'elements'],
    'ssr_child_care_needs' => ['render element' => 'elements'],
    'ssr_child_care_schema' => ['render element' => 'elements'],
    'ssr_cc_deviation' => ['render element' => 'elements'],
    'ssr_cc_deviation_student' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for child care templates.
 *
 * Default template: ssr-child-care.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the child care information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_ssr_child_care(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Prepares variables for child care placement templates.
 *
 * Default template: ssr-child-care-placement.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the child care placement information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_ssr_child_care_placement(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}


/**
 * Prepares variables for child care needs templates.
 *
 * Default template: ssr-child-care-needs.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the child care needs information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_ssr_child_care_needs(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Prepares variables for child care schema templates.
 *
 * Default template: ssr-child-care-schema.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the child care schema information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_ssr_child_care_schema(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Prepares variables for child care schema deviation templates.
 *
 * Default template: ssr-cc-deviation.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the child care schema deviation information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_ssr_cc_deviation(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Prepares variables for child care schema deviation student templates.
 *
 * Default template: ssr-cc-deviation-student.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the child care schema deviation student information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_ssr_cc_deviation_student(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
