simple_school_reports_entities.ssr_meeting_type.*:
  type: config_entity
  label: 'Meeting type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
