<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Site\Settings;
use Drupal\simple_school_reports_absence_make_up\CourseAttendanceReportAbsenceMakeupFormAlter;
use Drupal\simple_school_reports_core\Service\ReplaceTokenServiceInterface;

/**
 * Implements hook_views_query_alter().
 */
function simple_school_reports_help_views_query_alter(\Drupal\views\ViewExecutable $view, \Drupal\views\Plugin\views\query\QueryPluginBase $query) {
  if ($view->id() === 'help_pages' && $view->current_display === 'context') {

    $contexts_json = urldecode(\Drupal::request()->get('contexts', '[]'));
    $contexts = json_decode($contexts_json);

    if (!is_array($contexts) || empty($contexts)) {
      return;
    }

    foreach ($contexts as &$context) {
      $context = str_replace('/', '\/', $context);
    }

    foreach ($query->where as &$condition_group) {
      foreach ($condition_group['conditions'] as &$condition) {

        if (!empty($condition['field']) && $condition['field'] === 'node__field_context.field_context_value') {
          $condition['value'] = '^' . implode('$|^', $contexts) . '$';
        }
      }
    }
  }
}
