<?php

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function simple_school_reports_extra_adaptations_taxonomy_term_presave(\Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->bundle() === 'extra_adaptations' && $entity->isNew()) {
    $entity->set('name', 'Extra anpassning');
  }
}

/**
 * Implements hook_form_alter().
 */
function simple_school_reports_extra_adaptations_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id === 'taxonomy_term_extra_adaptations_form') {
    $form['relations']['#access'] = FALSE;
    unset($form['actions']['overview']);
    $form['#attached']['library'][] = 'simple_school_reports_extra_adaptations/extra_adaptations_form';
  }

  if ($form_id === 'views_exposed_form') {
    /** @var \Drupal\views\Entity\View $view */
    if ($view = $form_state->get('view')) {
      if ($view->id() === 'students' && $view->current_display === 'extra_adaptations') {
        if (!empty($form['field_extra_adaptation_target_id']['#options'])) {
          /** @var \Drupal\taxonomy\TermStorageInterface $term_storage */
          $term_storage = \Drupal::entityTypeManager()->getStorage('taxonomy_term');
          foreach ($form['field_extra_adaptation_target_id']['#options'] as $tid => &$label) {
            $extra_adaption = $term_storage->load($tid);
            if (!$extra_adaption) {
              if (is_numeric($tid)) {
                unset($form['field_extra_adaptation_target_id']['#options'][$tid]);
              }
              continue;
            }
            $label = $extra_adaption->get('field_extra_adaptation')->value;
            // Truncate to 50 characters, use '...' if needed.
            if (strlen($label) >= 50) {
              $label = substr($label, 0, 47) . '...';
            }
          }
        }
      }
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function simple_school_reports_extra_adaptations_paragraph_presave(\Drupal\paragraphs\ParagraphInterface $entity) {
  if ($entity->bundle() === 'extra_adaptation') {
    $extra_adaptation_target_id = $entity->get('field_extra_adaptation')->target_id;
    if (!$extra_adaptation_target_id) {
      $entity->set('field_school_subjects', []);
    }
  }
}
