<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function simple_school_reports_constrained_user_list_entity_bundle_field_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type, $bundle) {
  if ($entity_type->id() === 'user') {
    if (!empty($fields['field_birth_date_source'])) {
      $fields['field_birth_date_source']->setDefaultValue('ssn');
    }

    if (!empty($fields['field_ssn'])) {
      $fields['field_ssn']->setRequired(TRUE);
    }
  }
}

/**
 * Implements hook_entity_field_access().
 */
function simple_school_reports_constrained_user_list_entity_field_access($operation, \Drupal\Core\Field\FieldDefinitionInterface $field_definition, \Drupal\Core\Session\AccountInterface $account, ?\Drupal\Core\Field\FieldItemListInterface $items = NULL) {
  if ($field_definition->getName() === 'field_birth_date_source') {
    return \Drupal\Core\Access\AccessResult::forbidden();
  }

  return \Drupal\Core\Access\AccessResult::neutral();
}
